### ISSUE TITLE
Criware iwaihime (english steam)

### ISSUE THREAD

**Issue by imKota** [YuriSizuku/GalgameReverse#1]
Hello @YuriSizuku!

Is there any way to update the length of the string?
Since after packing the text, everything breaks down if the translated string is longer than the original one.

Game Iwaihime english.
1.m it's english translation
[data.zip](https://github.com/YuriSizuku/GalgameReverse/files/6904012/data.zip)
[binary_text_decode.txt](https://github.com/YuriSizuku/GalgameReverse/files/6904011/binary_text_decode.txt)

**Comment by YuriSizuku** [comment]
Sorry to reply late.  This is because there are index pointer of text, length of text,  as well as the jump options in the binary script. If you want to make the text longer, you need to have a future analyze of these opcodes in the script. After that, you can rebuild the index pointer.

**Comment by imKota** [comment]
Hello, @YuriSizuku!
Thanks for the answer!

Well, that's what I thought. And I tried to do something myself.

`○01804|00A405|019○ Noroihime: Curse Princess`

Line start address: **00A405**
![image](https://user-images.githubusercontent.com/24241471/127753131-1832eec2-1367-4f72-b6bf-fbe53d64edb2.png)

Line length: **019** will be **25** in decimal.
I tried changing the line length manually, but it didn't help.

Can't you tell me? I would be very grateful to you.

**Comment by YuriSizuku** [comment]
The third number 019 is the original size of the string.  As binary_text.py is a common tool for binary script, this only support for import text no longer than origin. Depending on the game, some can be import longer without modify. As for Iwaihime,  you need to modify the length in the binary script. For example, this opcode length (including text) is 6A.
![opcode_length](https://user-images.githubusercontent.com/15275959/127763933-31f4f172-b016-429d-b9df-b0b507117a07.png)

**Comment by YuriSizuku** [comment]
> Hello, @YuriSizuku!
> Thanks for the answer!
> 
> Well, that's what I thought. And I tried to do something myself.
> 
> `○01804|00A405|019○ Noroihime: Curse Princess`
> 
> Line start address: **00A405**
> ![image](https://user-images.githubusercontent.com/24241471/127753131-1832eec2-1367-4f72-b6bf-fbe53d64edb2.png)
> 
> Line length: **019** will be **25** in decimal.
> I tried changing the line length manually, but it didn't help.
> 
> Can't you tell me? I would be very grateful to you.

I think you can refer to the https://github.com/mchubby/yetireg_tools to parse opcode. I found that the file structure is very similar to iwaihime.

**Comment by Lorditler** [comment]
> Game Iwaihime english. 1.m it's english translation [data.zip](https://github.com/YuriSizuku/GalgameReverse/files/6904012/data.zip) [binary_text_decode.txt](https://github.com/YuriSizuku/GalgameReverse/files/6904011/binary_text_decode.txt)

Hello, @imKota!. Sorry to interrupt, but I would like to ask if you have the extracted Japanese text of this novel?

**Comment by imKota** [comment]
@Lorditler hey!
[script_decodec.zip](https://github.com/YuriSizuku/GalgameReverse/files/9217034/script_decodec.zip)

**Comment by Kaii-h** [comment]
@Lorditler, Or like this [jap(1).txt](https://github.com/YuriSizuku/GalgameReverse/files/9217226/jap.1.txt).
Encoding Shift-JIS.

**Comment by B1Ancc** [comment]
Hi, @imKota. My apologies for digging this thread, but how did you pack the script back into the game? Thank you in advance.
