### ISSUE TITLE
About FFA engine

### ISSUE THREAD

**Issue by Cosetto** [YuriSizuku/GalgameReverse#10]
Hello again. I saw you revsered FFA engine, so since you have reversed SO4 and PT1 format, can you also check the SO5 and PT1 of [this game](https://vndb.org/v17492) too?
I have some sample scripts here
[Script.zip](https://github.com/YuriSizuku/GalgameReverse/files/13634387/Script.zip)

**Comment by YuriSizuku** [comment]
The structure is similar but ome opcode changed. I edit a little from so4 to extract so5 format. 
It should be worked for the example. 
[GatedCommunity_SO5.zip](https://github.com/YuriSizuku/GalgameReverse/files/13634746/GatedCommunity_SO5.zip)

**Comment by Cosetto** [comment]
Can you check the PT1 image too?
```
  File "D:\J02WIN\pt1\pt1.py", line 91, in <module>
    main()
  File "D:\J02WIN\pt1\pt1.py", line 83, in main
    export_pt1(sys.argv[2], outpath)
  File "D:\J02WIN\pt1\pt1.py", line 44, in export_pt1
    rawdata, rawsize = amalzss.decode_lzss(data[pt1.size: ], outpath=outpath)
  File "D:\J02WIN\pt1\lzss.py", line 38, in decode_lzss
    raise ValueError(f"decode data size wrong {dstsize:x}!={rawsize:x}")
ValueError: decode data size wrong 19a20!=30000
```
[pt1.zip](https://github.com/YuriSizuku/GalgameReverse/files/13635676/pt1.zip)
And also, is it possible to make packer tool? [GARbro's format](https://github.com/morkt/GARbro/blob/b09ee4570ccb1daf6ac56710ee8934dc0b8baeb0/ArcFormats/Ffa/ArcBlackPackage.cs#L101-L141)
An example archive
[J02WIS.zip](https://github.com/YuriSizuku/GalgameReverse/files/13635693/J02WIS.zip)

**Comment by Cosetto** [comment]
It looks like the game can read SO5 files directly, but it crashed because SO5 needs to be encoded back with Lzss since GARbro decode them when extracting. [link](https://github.com/morkt/GARbro/blob/b09ee4570ccb1daf6ac56710ee8934dc0b8baeb0/ArcFormats/Ffa/ArcBlackPackage.cs#L77C1-L98C6)
