### ISSUE TITLE
Criware xtx format image encode

### ISSUE THREAD

**Issue by Todaymayfly** [YuriSizuku/GalgameReverse#11]
Hi!

It's me again.

Thanks to your help, I've just finished translation of criware game.

The only remaining problem is the images(CGs).

The images exist as xtx format in cpk file.

https://github.com/vn-tools/arc_unpacker/issues/54

https://github.com/vn-tools/arc_unpacker/blob/master/src/dec/cri/xtx_image_decoder.cc

He decoded xtx images, but did not encode.

I think it would be possible to build encoding code based on this code, as you did with `xtx_font.py`

But I don't know how.

I have no idea about dealing with images.

Please help.

xtx image sample:
[641.zip](https://github.com/YuriSizuku/GalgameReverse/files/15211013/641.zip)

**Comment by Todaymayfly** [comment]
Hey!

I've finished this work successfully.

I simply reversed your code like this, 

```
def gray2xtx_tex0(gray):
    height, width, alpha = gray.shape
    data = bytearray((height+16)*width*4)
    print(height,width,height*width)

for i in range((height+16)*width):

    abs_x = get_x(i, width, 4)
    abs_y = get_y(i, width, 4)
    if abs_y >= height or abs_x >= width:
        continue

    idx = i * 4
    x = get_x(i, width, 4);
    y = get_y(i, width, 4);

    data[idx] = gray[y][x][3]  
    data[idx + 1] = gray[y][x][2] 
    data[idx + 2] = gray[y][x][1]
    data[idx + 3] = gray[y][x][0]      

return data
```

It works anyway.

Thanks!

**Comment by Todaymayfly** [comment]
oh, sure.

but... that's all I modified.

You can just put that modified function in YuriSizuku's code: `xtx_font.py`

The whole code is like this

`import os
import struct
import numpy as np
import cv2
import csv

def get_x(i, width, level): 
    # level means nesting times
    v1 = (level >> 2) + (level >> 1 >> (level >> 2))
    v2 = i << v1
    # 8X8 3f, 
    v3 = (v2 & 0x3F) + ((v2 >> 2) & 0x1C0) + ((v2 >> 3) & 0x1FFFFE00)
    return ((((level << 3) - 1) & ((v3 >> 1) ^ ((v3 ^ (v3 >> 1)) & 0xF))) >> v1)+  ((((((v2 >> 6) & 0xFF) + ((v3 >> (v1 + 5)) & 0xFE)) & 3)
            + (((v3 >> (v1 + 7)) % (((width + 31)) >> 5)) << 2)) << 3)

def get_y(i, width, level):
    v1 = (level >> 2) + (level >> 1 >> (level >> 2))
    v2 = i << v1
    v3 = (v2 & 0x3F) + ((v2 >> 2) & 0x1C0) + ((v2 >> 3) & 0x1FFFFE00)
    return ((v3 >> 4) & 1) + ((((v3 & ((level << 6) - 1) & -0x20)
            + ((((v2 & 0x3F)
                + ((v2 >> 2) & 0xC0)) & 0xF) << 1)) >> (v1 + 3)) & -2) + ((((v2 >> 10) & 2) + ((v3 >> (v1 + 6)) & 1)
            + (((v3 >> (v1 + 7)) // ((width + 31) >> 5)) << 2)) << 3)

def gray2xtx_tex0(gray):
    height, width, alpha = gray.shape
    data = bytearray((height)*width*4)
    print(height,width,height*width)

    for i in range((height)*width):

        abs_x = get_x(i, width, 4)
        abs_y = get_y(i, width, 4)
        if abs_y >= height or abs_x >= width:
            continue

        idx = i * 4
        x = get_x(i, width, 4);
        y = get_y(i, width, 4);

        data[idx] = gray[y][x][3]  
        data[idx + 1] = gray[y][x][2] 
        data[idx + 2] = gray[y][x][1]
        data[idx + 3] = gray[y][x][0]      

    return data

def xtx_font_build(inpath, outpath="rebuild.xtx"):
    gray = cv2.imread(inpath, cv2.IMREAD_UNCHANGED)
    print(gray.shape)
    height, width, alpha = gray.shape
    with open(outpath, 'wb') as fp:
        fp.write(b"\x10\x00\x00\x00\x20")
        fp.write(b"\x80\x39\x00\x00")
        fp.write(b"\x00\x00\x00\x00\x00\x00\x00")
        fp.write(b"xtx\0")
        fp.write(b"\x00\x00\x00\x00")
        fp.write(int.to_bytes(width, 4, 'big'))
        fp.write(int.to_bytes((height), 4, 'big'))
        fp.write(int.to_bytes(width, 4, 'big'))
        fp.write(int.to_bytes(height, 4, 'big'))        
        fp.write(int.to_bytes(0, 4, 'big'))
        fp.write(int.to_bytes(0, 4, 'big'))
        data = gray2xtx_tex0(gray)
        fp.write(data)

def main():
    if len(os.sys.argv) <= 2:
        print("xtxfont e pngpath [xtxpath]")
        return 0
    
    if os.sys.argv[1].lower() == 'e':
        outpath = "out.xtx" if len(os.sys.argv)<=3 else os.sys.argv[3]
        xtx_font_build(os.sys.argv[2], outpath)
    else: print("invalid parameter")


if __name__ == "__main__":
    main()
    #debug()`
    
    
 about header information, I used hard coding (I write down header directly),
    
 So you should change that part.

**Comment by Cosetto** [comment]
@Todaymayfly Is it possible to add support for this xtx of Iwaihime?
[1.zip](https://github.com/YuriSizuku/GalgameReverse/files/15441450/1.zip)
It's the second type xtx, which is headerless, base on this https://github.com/morkt/GARbro/blob/master/ArcFormats/Cri/ImageXTX.cs

**Comment by Todaymayfly** [comment]
It looks quite different.

It appears to be composed of multiple xtx combinations.

In the header, every 16 bytes indicate the starting address of each xtx header in little-endian format.

(For example, in 0.xtx, the first xtx address is 09e0, and the next is 21ca00.)

After that, it writes the image information every 16 bytes, which is probably the result of the function ReadTex2.

(like '05 00 ff ff ff ff ff ff / cb 44 89 61 75 55 fd 35')

But... I have no idea what it is.

So, I guess you should understand the function ReadTex2 and reverse it.

I'm sorry I couldn't be of more help.

I've never learned programming things.

Good luck with your translation.

**Comment by MishaIac** [comment]
> @Todaymayfly Is it possible to add support to encode this xtx of Iwaihime? [xtx.zip](https://github.com/YuriSizuku/GalgameReverse/files/15441532/xtx.zip) We can view the image with GARbro after decoding the files. ![image](https://private-user-images.githubusercontent.com/81801486/333770353-4fc64ede-3d2a-4dce-bd71-19ae1cfa2f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTc4MjcsIm5iZiI6MTcyODExNzUyNywicGF0aCI6Ii84MTgwMTQ4Ni8zMzM3NzAzNTMtNGZjNjRlZGUtM2QyYS00ZGNlLWJkNzEtMTlhZTFjZmEyZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA4Mzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTQ4YzM3YmFjY2FkNjc2M2ZiZWNlODc0Y2Y4ODE5MGZjYWI5ZjEzMmY4ZGU1OTI0YWQzYzNlMjg4ODgzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKN8HqweqX70O_VOC8C2931eH7pzvgJacrvPaemIOBo) It's the second type xtx, which is headerless, base on this https://github.com/morkt/GARbro/blob/master/ArcFormats/Cri/ImageXTX.cs

done here: https://github.com/MishaIac/iwaihime-tool/tree/main/xtx_tex2_tool
need wand and installed ImageMagick to work

**Comment by MishaIac** [comment]
> > @Todaymayfly Is it possible to add support to encode this xtx of Iwaihime? [xtx.zip](https://github.com/YuriSizuku/GalgameReverse/files/15441532/xtx.zip) We can view the image with GARbro after decoding the files. ![image](https://private-user-images.githubusercontent.com/81801486/333770353-4fc64ede-3d2a-4dce-bd71-19ae1cfa2f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTc4MjcsIm5iZiI6MTcyODExNzUyNywicGF0aCI6Ii84MTgwMTQ4Ni8zMzM3NzAzNTMtNGZjNjRlZGUtM2QyYS00ZGNlLWJkNzEtMTlhZTFjZmEyZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA4Mzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTQ4YzM3YmFjY2FkNjc2M2ZiZWNlODc0Y2Y4ODE5MGZjYWI5ZjEzMmY4ZGU1OTI0YWQzYzNlMjg4ODgzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EKN8HqweqX70O_VOC8C2931eH7pzvgJacrvPaemIOBo) It's the second type xtx, which is headerless, base on this https://github.com/morkt/GARbro/blob/master/ArcFormats/Cri/ImageXTX.cs
> 
> done here: https://github.com/MishaIac/iwaihime-tool/tree/main/xtx_tex2_tool need wand and installed ImageMagick to work not tested in game, but at least GARbro decodes them correctly

sys.cpk archives tool also done: https://github.com/MishaIac/iwaihime-tool/tree/main/sys_cpk_tool
