### ISSUE TITLE
Bruns libscr.dll missing

### ISSUE THREAD

**Issue by HHCThuan** [YuriSizuku/GalgameReverse#12]
Maybe I'm missing something, but the bruns decryptor needs to load libscr.dll. But I can't find this dll anywhere or a way to install it.

**Comment by YuriSizuku** [comment]
You need to get this dll from the target game.

**Comment by HHCThuan** [comment]
Thanks, I found the libscr.dll and put it in the same folder as the decryptor, but it can't load the dll, even after I specify the absolute path for the dll

**Comment by HHCThuan** [comment]
After printing GetLastError, it says "is not a valid Win32 application.", so there's a problem with the libscr.dll?
