### ISSUE TITLE
Something about hibiki_test_ks.py

### ISSUE THREAD

**Issue by Sisulizer** [YuriSizuku/GalgameReverse#3]
I just found out that the code won't catch the text with blank space before it like in p3 and p4
![image](https://user-images.githubusercontent.com/91543117/184050567-bebd91ab-9db6-43a2-ab08-4be80a8ddd93.png)
[01姉_00_01.zip](https://github.com/YuriSizuku/GalgameReverse/files/9305422/01._00_01.zip)

**Comment by YuriSizuku** [comment]
Sorry for reply lately. 
Thank you very much for showing the problem. 
I think I have fix this blank space line problem.
