### ISSUE TITLE
Cannot find azsystem folder

### ISSUE THREAD

**Issue by namlhse02285** [YuriSizuku/GalgameReverse#4]
I want to translate 穢翼のユースティア (Artemis Engine), I did unzip .pfs file and got .asb scenerio script file. I want to decrypt it, I searched but only found result over here.
But I cannot found src/azsystem/lamune_hook.js. Could you please re-up that file?

**Comment by YuriSizuku** [comment]
Thank you for your question. 
As the analysis for azsystem is not perfect, there are lots of  fixed address for lamune.
So that I didin't upload these scripts yet.  I'm not sure whether these codes work well for the other games. 
I uploaded the lamune scripts now and I hope it will help you.

**Comment by namlhse02285** [comment]
Seem like you fixed array's value to Lamune, and I'm sorry that I don't know how to use your source code.
But I found out that other repo can handle asb file quite good (it can dump asb to json and put translation back, I tested with 穢翼のユースティア, worked)
I think it has some useful stuff, you can search "VNTextPatch" btw
