### ISSUE TITLE
【I need help!】About GalgameReverse

### ISSUE THREAD

**Issue by mochangan** [YuriSizuku/GalgameReverse#5]
Hello,

I find some trouble to use your tool named GalgameReverse

and I need your help about how to use GalgameReverse to extract the game Narcissus ナルキッソス～もしも明日があるなら file(Now I had extract sound and bgm,but have no way to background photo, and I need there photo to write my Narcissus article)

maybe my English make you feel unfluent or clumsy, but I try my best and feel sorry for you

and here are  Chinese issue  

关于GalgameReverse

非常抱歉打扰到您，我是在看到 水仙：如果还有明天携带版（PSP版风铃汉化组汉化）的发布后游玩并且在尝试解包的过程遇到困难来向您求助的，我是在贵组的专栏看到您的留言注意到您是负责程序部分的大佬(develseed)，并且初步尝试和研究过您留下的工具ReverseUtil 无果后出于无奈来这里留言给您，

先直接说问题：我在解游戏的iso镜像包时已经解出了 OPED动画、语音、音效，但是从包里的bg.afs提取出的（这应该是背景图片吧）后缀名为.spc格式的文件是真的找遍中文互联网都找不出方法了。

如果您需要了解我解包过程更具体的情况可以看我在B站发布的专栏cv24821012  

因为我现在一边推本作一边写本作的专栏需要配合相应的插图，但是去画廊一张一张截效率确实低了点而且画廊并不完全包含全部场景图，因此还请您教简单我如何使用您的工具或者教我如何解包出图片文件，万分感谢

这是我的联系方式（具体情况可以的话请您加我QQ或者B站上直接私信我，Github不经常看）

QQ：715384475

B站ID：守秘莫长安 

Twitter：lushi43526079

**Comment by YuriSizuku** [comment]
spc文件是有一层lzss压缩的，用(Narcissus_lzss.py)[https://github.com/YuriSizuku/GalgameReverse/blob/master/src/hobibox/Narcissus_lzss.py]解压缩后再用[Narcissus_lbg.py](https://github.com/YuriSizuku/GalgameReverse/blob/master/src/hobibox/Narcissus_lbg.py)还原成png。

**Comment by mochangan** [comment]
非常感谢大佬，原来是我一开始找错了程序，一开始按大佬的留言是跳转到GalgameReverse的仓库，但是被简介误导到ReverseUtil那里去了，然后折腾了一会CUI毫无头绪，当时放弃过一次（大概一周前），后来推完这水仙携带版里水仙1的内容后想了想还是再挣扎一下，接着折腾也是没有结果就来您这里求助了，原来是python程序，因为之前解包其他汉硬游戏基本都能找到对应有GUI的工具，只有CUI的工具做超分辨率的时候见得多，所以一开始看到您的ReverseUtil人先怯了。再次感谢您的指点，先去看py源码了。(*^▽^*)
Thanks

**Comment by muato-jsq** [comment]
大佬牛批🤩
