### ISSUE TITLE
9-nine- switch .fnt (Entergram's engine)

### ISSUE THREAD

**Issue by imKota** [YuriSizuku/GalgameReverse#7]
Hello, @YuriSizuku!

Can you help with this font ?
![111](https://github.com/YuriSizuku/GalgameReverse/assets/24241471/69a7341e-1137-4e5c-8bb0-dbe0d85495b8)

game: https://vndb.org/r83944
font: [font_00.fnt.zip](https://github.com/YuriSizuku/GalgameReverse/files/12145868/font_00.fnt.zip)

https://github.com/DCNick3/shin/blob/master/shin-core/src/format/font.rs
https://github.com/andOlga/kaleido/tree/saku/fnt

**Comment by YuriSizuku** [comment]
The font seems to be encrypted or compressed.  Have you try to decrypt or decompress at first ?

**Comment by Cosetto** [comment]
@imKota For switch version, you can seek help from [this](https://github.com/masagrator/NXGameScripts). He made tools for 9-nine switch version, so I think he can help.

**Comment by imKota** [comment]
> The font seems to be encrypted or compressed. Have you try to decrypt or decompress at first ?

Nope(

**Comment by imKota** [comment]
> @imKota For switch version, you can seek help from [this](https://github.com/masagrator/NXGameScripts). He made tools for 9-nine switch version, so I think he can help.

Thanks, but I only have a problem with the font.
So the repository won't help me with anything.

**Comment by imKota** [comment]
> @imKota For switch version, you can seek help from [this](https://github.com/masagrator/NXGameScripts). He made tools for 9-nine switch version, so I think he can help.

@Cosetto Thanks, but I only have a problem with the font.
So the repository won't help me with anything.

**Comment by imKota** [comment]
@YuriSizuku any news?

**Comment by YuriSizuku** [comment]
> @YuriSizuku any news?

It seems that this font was compressed by lz77. Later I will check it.

**Comment by YuriSizuku** [comment]
Sorry for the late reply. 
I made a script for parsing this kind of font. You can use command to extract glphys. Then modify and append the data to the end of font. 

see [9nine_fnt.py](https://github.com/YuriSizuku/GalgameReverse/blob/master/project/entergram/9nine_fnt.py)

I just tested append origin glyph in the end of the fnt file. 
I did't test the details of the result,  you can edit and test the glphy parameter as well.  

``` python
python 9nine_fnt.py e font_00.fnt font_00.zip
python 9nine_fnt.py a font_00.fnt font_00.zip font_rebuild.fnt
```

Here are the glphys in fnt
[font_00.zip](https://github.com/YuriSizuku/GalgameReverse/files/13628722/font_00.zip)
