### ISSUE TITLE
Requesting script tool for RealLive engine

### ISSUE THREAD

**Issue by Cosetto** [YuriSizuku/GalgameReverse#9]
The engine is kinda similar to Siglus engine. For unpacking/packing Seen.txt, [arc_conv](https://github.com/amayra/arc_conv) can do the job
You can check in [this issue](https://github.com/satan53x/SExtractor/issues/1#issuecomment-1692699401) about xoring the script after unpacking, you also have to xor before packing back Seen.txt, you can use my version here
[xor.zip](https://github.com/YuriSizuku/GalgameReverse/files/12448430/xor.zip)
The real problem is the line breaker for English script, RealLive doesn't use "\n" but something like "23/00/03/C9/00/00/00/00/40/??(the length of next line, maybe?)/00"
![image](https://github.com/YuriSizuku/GalgameReverse/assets/81801486/31ae1402-65ac-45a3-8c75-3cf5874dc52a)
![image](https://github.com/YuriSizuku/GalgameReverse/assets/81801486/4107ffb5-78fb-47ae-9414-e81501dd3a6a)
Although [text_conv](https://github.com/amayra/arc_conv/blob/master/text_conv/rlseen.c) can deal with the script, but it doesn't have option for line breaker.

**Comment by Cosetto** [comment]
Forgot to mention, the script in the pic is from Niizuma Shino.

**Comment by YuriSizuku** [comment]
Sorry for the late replay. I think you can try to use this tool. 
[reallive_tools.zip](https://github.com/YuriSizuku/GalgameReverse/files/13626536/reallive_tools.zip)

**Comment by Cosetto** [comment]
Looks like the tools doesn't with Haadashi's RealLive. Anyway, thank you very much.
